# simtemp/kernel/Kbuild

# Module name (without .ko extension)
obj-m += nxp_simtemp.o
obj-m += nxp_simtemp_device.o

# Header file paths
ccflags-y += -I$(src)

# Module version (optional)
MODULE_VERSION := 1.0